config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get   "/vendors",                 to: "vendors#index"
  get   "/vendors/new",             to: "vendors#new"
  post  "/vendors",                 to: "vendors#create"
  get   "/vendors/login",           to: "vendors#login_page"
  post  "/vendors/login",           to: "vendors#login"
  get   "/vendors/logout",          to: "vendors#logout"

  get   "/vendors/:id",             to: "vendors#show"
  get   "/vendors/:id/my_products", to: "vendors#my_products"
  get   "/vendors/:id/add_product", to: "products#new"
  get   "/vendors/:id/add_market",  to: "market#new"
  get   "/vendors/:id/edit",        to: "vendors#edit"
  get   "/vendors/:id/sales",       to: "vendors#sales"
  put   "/vendors/:id",             to: "vendors#update"
  get   "/vendors/:id/destroy",     to: "vendors#delete"

  get   "/products",                to: "products#index"
  get   "/products/new",            to: "products#new"
  post  "/products",                to: "products#create"
  get   "/products/:id",            to: "products#show"
  get   "/products/:id/edit",       to: "products#edit"
  put   "/products/:id/",           to: "products#update"
  get   "/products/:id/destroy",    to: "products#delete"

  get   "/sales/new/:id",           to: "sales#new"
  post  "/sales/create",            to: "sales#create"
  get   "/sales/:id",               to: "sales#show"

  get   "/markets",                 to: "market#index"
  get   "/markets/new",             to: "market#new"
  post  "/markets/create",          to: "market#create"

  get   "/markets/:id",             to: "market#show"
  put   "/markets/:id",             to: "market#update"
  post  "/markets/:id",             to: "market#create"
  get   "/markets/:id/destroy",     to: "market#delete"

  get   "/markets/:id/edit",        to: "market#edit"

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
  has_many :products, through: :vendors
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor

  def path
    "/products/#{self.id}"
  end

  def edit_path
    "/products/#{self.id}/edit"
  end

  def delete_path
    "/products/#{self.id}/destroy"
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products

  def path
    "/vendors/#{self.id}"
  end

  def edit_path
    "/vendors/#{self.id}/edit"
  end

  def delete_path
    "/vendors/#{self.id}/destroy"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception # comment this out to allow writing forms in raw HTML

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/market_controller.rb
class MarketController < ApplicationController


  def new
    @market = Market.new
  end

  def index
    @markets = Market.all.sort_by {|market| market.name}
  end

  def create
    @market = Market.create(req_per_params)
    if session[:vendor_id]
      Vendor.update(session[:vendor_id], market_id: @market.id)
    end
    redirect_to "/markets/#{@market.id}"
  end

  def edit
    find_market
  end

  def show
    find_market
  end

  def update
    find_market
    @market.update(req_per_params)
    redirect_to "/markets/#{@market.id}"
  end

  def delete
    find_market
    @market.destroy
    redirect_to "/markets"
  end

  private

  def req_per_params
    params.require(:market).permit(:name, :street_address, :city, :state, :zipcode)
  end

  def find_market
    @market = Market.find(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to "/vendors/#{@product.vendor_id}"
    else
      render :new
    end
  end

  def edit
    find_product
  end

  def show
    find_product
    @sales = Sale.where("product_id='#{@product.id}'")
    @vendor = Vendor.find(@product.vendor_id)
  end

  def update
    find_product
    @product.update(params.permit(:name, :description, :price))
    if @product.save
      redirect_to "/products/#{@product.id}"
    else
      render :edit
    end
  end

  def delete
    find_product
    @product.destroy
    redirect_to "/products"
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :vendor_id)
  end

  def find_product
    @product = Product.find(params["id"])
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def new
    @product = product
    @sale = Sale.new
  end

  def create
    @sale = Sale.create(params.require(:sale).permit(:number_sold, :cost, :product_id))
    puts params.inspect
    puts "*"*80
    puts @sale.number_sold
    redirect_to "/sales/#{@sale.id}"
  end

  def show
    @sale = Sale.find(params[:id])
    @product = Product.find(@sale.product_id)
  end

  private
  def vendor
    @vendor = Vendor.find(params[:sale][:vendor_id])
  end

  def product
    @product = Product.find(params[:id])
  end


end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      session[:vendor_id] ||= @vendor.id
      redirect_to "/vendors/#{@vendor.id}"
    else
      render :new
    end
  end

  def show
    if session[:vendor_id]
      puts "session:", session
      @loggedin = true
    end
    find_vendor
    @market = @vendor.market_id ? Market.find(@vendor.market_id) : nil
  end

  def edit
    find_vendor
  end

  def sales
    find_vendor
    @sales = []
    @products = Product.where(vendor_id: @vendor.id).each do |product|
      @sales += Sale.where(product_id: product.id)
    end
  end

  def my_products
    find_vendor
  end

  def update
    find_vendor
    @vendor.update(vendor_params)
    if @vendor.save
      redirect_to "/vendors/#{@vendor.id}"
    else
      render :edit
    end
  end

  def delete
    find_vendor
    products = Product.where(vendor_id: @vendor.id)
    products.each { |product| product.destroy }
    session[:vendor_id] = nil
    @vendor.destroy
    redirect_to "/vendors"
  end

  def login
    find_vendor
    session[:vendor_id] ||= @vendor.id
    redirect_to "/vendors/#{@vendor.id}"
  end

  def logout
    session[:vendor_id] = nil
    redirect_to "/"
  end

  private
  def vendor_params
    params.require(:vendor).permit(:name, :market_id, :description, :website, :email, :phone)
  end

  def find_vendor
    @vendor = Vendor.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find Farmers Markets</title>
</head>

<body>

<br><br>Placeholder peppers!<br>
<img center src="/pepperpic.jpg">

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="/css/layout.css" rel="stylesheet">
  <title>Far Mar</title>
</head>
<body>
  <header>
    <div id="opaque-image"></div>
    <span class="title">
      <a href="/"><b>FarMar</b></a>
    </span><span class="subtitle">
    <b>The ultimate guide to farmers' markets in America</b></span>
    <nav>
      <ul class="horizontal-list">

        <li><a href="/">Home</a></li>

        <li><a href="/markets">Markets</a>
          <ul class="dropdown">
            <% Market.all.each do |market| %>
              <li>
                <a href="/markets/<%=market.id%>"><%=market.name%></a>
              </li>
            <% end %>
          </ul></li>

        <li><a href="/vendors">Vendors</a>
          <ul class="dropdown">
            <% Vendor.all.each do |vendor| %>
              <li>
                <a href="/vendors/<%=vendor.id%>"><%=vendor.name%></a>
              </li>
            <% end %>
          </ul></li>

        <li><a href="/products">Products</a></li>

      <% if session[:vendor_id] %>
        <% vendor = Vendor.find(session[:vendor_id]) %>
        <li class="user"><a href="/vendors/<%=vendor.id%>"><%=vendor.name%></a>
          <ul class="dropdown">
            <li><a href="/markets/<%=vendor.market_id%>">My market</a></li>
            <li>
              <a href="/vendors/<%=vendor.id%>/my_products">My products</a></li>
            <li><a href="/vendors/<%=vendor.id%>/add_product">Add product</a></li>
            <li style="text-align: center">&mdash;</li>
            <li>Vendor ID: <%= vendor.id %></li>
            <li><a href="/vendors/logout">Log out</a></li>
          </ul></li>

      <% else %>
        <li class="user"><a href="/vendors/login">Log in</a></li>
      <% end %>
    </ul>
    </nav>
    <!-- <hr> -->
  </header>

<div class="mainstuff">

<%= yield %>

</div>

<!-- <footer>
  <br>
  <% if session[:vendor_id] %>
    <a href= "/vendors/logout">Log out <%= Vendor.find(session[:vendor_id]).name %></a>
  <% else %>
    <a href= "/vendors/login" >Login</a>
  <% end %>
</footer> -->
</body>
</html>

app/views/market/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit a market</title>
</head>

<body>

  <h2>Edit <%=@market.name%></h2>

  <form method="POST" action="/markets/<%= @market.id %>">
    <input type="hidden" name="_method" value="PUT"/>

    <table>
      <tr><td>Name:</td><td> <input type="text" name="market[name]" value="<%= @market.name %>"/></td> </tr>
      <tr><td>Street Address:</td><td><input type="text" name="market[street_address]" value="<%= @market.street_address %>"</td></tr>
      <tr><td>City:</td><td><input type="text" name="market[city]" value="<%= @market.city %>"/></td></tr>
      <tr><td>State:</td><td><input type="text" name="market[state]" value="<%= @market.state %>"</td></tr>
      <tr><td>Zip code:</td><td><input type="text" name="market[zipcode]" value="<%= @market.zipcode %>"/></td></tr>
    </table>

    <input type="submit" value="Make Changes"/>
  </form>

  <a class="button" href="/markets/<%= @market.id %>">Cancel</a>
</body>
</html>

app/views/market/index.html.erb
<html>
<head>
  <title>All markets</title>
</head>

<body>
  <h2>Markets</h2>
  <ul>
    <% @markets.each do |market| %>
      <li><a href="/markets/<%=market.id%>"><%= market.name%></a></li>
    <% end %>
  </ul>

  <a class="button" href="/markets/new">Create New</a>
</body>
</html>

app/views/market/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Create a new market</title>
</head>

<body>

  <form method="POST" action="/markets/create">
    <table>
      <tr> <td>Name:</td> <td><input type="text" name="market[name]"/></td></tr>
      <tr> <td>Street address:</td> <td><input type="text" name="market[street_address]"/></td></tr>
      <tr> <td>City:</td> <td><input type="text" name="market[city]"/></td></tr>
      <tr> <td>State:</td> <td><input type="text" name="market[state]"/></td></tr>
      <tr> <td>Zip Code:</td> <td><input type="text" name="market[zipcode]"/></td></tr>
  </table>

    <input type="submit" value="Create Market"/>
  </form>

  <a class="button" href="/markets">Cancel</a>

</body>
</html>

app/views/market/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All about <%=@market.name%></title>
</head>

  <body>
  <h2><%=@market.name%></h2>

  <%= @market.street_address %><br>
  <%= @market.city %>, <%= @market.state %> <%= @market.zipcode %><br>

  <h3>Vendors at <%=  @market.name %> </h3>
  <ul>
  <% Vendor.where(market_id: @market.id).each do |vendor| %>
    <li><a href="<%=vendor.path%>"><%=vendor.name%></a></li>
  <% end %>
  </ul>

  <% if session[:vendor_id] %>
    <% current_user = Vendor.find(session[:vendor_id]) %>
  <% end %>

  <% if current_user && current_user.market_id == @market.id %>
    <a class="button" href="/markets/<%=@market.id%>/edit">Edit</a>
    <a class="button" href="/markets/<%=@market.id%>/destroy">Delete</a>
    <a class="button" href="/markets/">Back to Market list</a>
  <% end %>

</body>
</html>

app/views/products/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit <%= @product.name %> </title>
</head>

<body>
<form action= "/products/<%= @product.id %>" method="POST">

  <input type="hidden" name="_method" value="PUT" />
  Name <input name="vendor[name]" value= "<%= @product.name %>" />
  Description <input name="vendor[description]" value= "<%= @product.description %>" />
  Price <input name="vendor[price]" value= "<%= @product.price %>" />

  <input type="submit"/>

</form>
</body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All products</title>
</head>

<body>
  <h1>List of all products</h1>
  <ul>
    <% Product.all.each do |product| %>
      <li>
        <a href= <%= product.path %> ><%= product.name %> </a>
      </li>
    <% end %>
  </ul>

</body>

</html>

app/views/products/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Add a product</title>
</head>

<body>
  <form method="POST" action="/products#create">
    Product name <input name="product[name]"/><br>
    Description <input name="product[description]"/><br>
    Price <input name="product[price]" type="number" step="0.01"/><br>
    <input type="hidden" name="product[vendor_id]" value= <%= params.permit(:id)["id"].to_i %> />

    <input type="submit"/>

  </form>

  <a class="button" href="/products/">Cancel</a>

  <!-- <%= form_for :product, url: products_path do |f| %> <!- -WHAT SORCERY IS THIS- -><!- - I don't know, so I'm going to write this in raw HTML so I get it. - ->
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :price %><br>
      <%= f.text_field :price %>

    <p>

      <%= f.hidden_field :vendor_id, value: params[:id].to_i %>
      <!- - http://stackoverflow.com/questions/16280341/hidden-field-in-rails-form - ->

      <%= f.submit %>
    </p>
  <% end %> -->
</body>
</html>

app/views/products/product_page.html.erb
<% product = Product.find(params[:id]) %>
<!-- <%= puts "*" * 80, product.vendor_id, "*" * 80 %> -->
<% vendor = Vendor.find(product.vendor_id) %>

<html>
<head>
  <title>All About <%= product.name %></title>
</head>

<body>
  <h1> <%= vendor.name %>'s <%= product.name %> </h1>
  <p> <%= product.description %> &mdash; $<%= product.price %></p>
  <a href = <%= product.edit_path %> >Edit</a>
  <!-- <a href = <%= product.delete_path %> >Delete</a> -->
  <form method="POST">
    <input type="submit"/>
  </form>
</body>

app/views/products/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All about <%= @product.name %></title>
</head>

<body>
  <h1> <%= @vendor.name %>'s <%= @product.name %> </h1>
  <p> <%= @product.description %> &mdash; $<%= @product.price %></p>
  <% if session[:vendor_id] == @vendor.id %>
    <% if @sales.length > 0 %>
      <% @sales.each do |sale|%>
        Sold <%= sale.number_sold %> at <%= sale.created_at %> for <%= number_to_currency(sale.cost) %>.<br>
      <% end %>
    <% end %>
    <a class="button" href = "/sales/new/<%=params[:id]%>">Make a Sale</a>
    <a class="button" href = <%= @product.edit_path %> >Edit</a>
    <a class="button" href = <%= @product.delete_path %> >Delete</a>
  <% end %>
  <a class="button" href= "/vendors/<%= @product.vendor_id %>">Back to <%= @vendor.name %></a>
</body>
</html>

app/views/sale/new.html.erb
<h2>New Sale of <%= @product.name %> </h2>

<form method="POST" action="/sale/show">
  <table>
    <tr><td>Price</td> <td><%= @product.price %></td></tr>
    <tr><td>Quantity</td> <td><input type="text" name="sale[:number_sold]"/></td></tr>
  </table>
  <input type="hidden" name="sale[cost]" value = "<%= @product.price %>"
  <input type="hidden" name="sale[product_id]" value="<%= @product.id %>"/>
  <input type="submit" value="Record Sale"/>
</form>

app/views/sales/new.html.erb
<h2>New Sale of <%= @product.name %> </h2>

<form method="POST" action="/sales/create">
  <table>
    <tr><td>Price</td> <td><%= @product.price %></td></tr>
    <tr><td>Quantity</td> <td><input type="text" name="sale[number_sold]"/></td></tr>
  </table>
  <input type="hidden" name="sale[cost]" value = "<%= @product.price %>"/>
  <input type="hidden" name="sale[product_id]" value="<%= @product.id %>"/>
  <input type="submit" value="Record Sale"/>
</form>
<a class="button" href="/products/<%= @product.id %>">Cancel</a>

app/views/sales/show.html.erb
<h2>Sale of <%= @product.name %></h2>
<table>
  <tr><td>Quantity sold:</td> <td> <%= @sale.number_sold.inspect %></td></tr>
  <tr><td>Sale price:</td> <td> <%= @sale.cost %> </td></tr>
  <tr><td>Sale time:</td> <td><%= @sale.created_at %> </td></tr>
  <tr><td>Sale id:</td> <td> <%= @sale.id %> </td></tr>
</table>
<a class="button" href="/products/<%= @product.id %>" > Back to <%= @product.name %> page</a><br>
<a class="button" href="/vendors/<%= @product.vendor_id %>"> Back to <%= Vendor.find(@product.vendor_id).name %> page</a>

app/views/vendors/add_product.html.erb
<html>
<head>
  <title>Add a product</title>
</head>

<body>
  <%= params.inspect %>
  <!-- <%= form_for :product, url: products_path do |f| %> <!- -WHAT SORCERY IS THIS- -><!- - I don't know, so I'm going to write this in raw HTML so I get it. - ->
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :price %><br>
      <%= f.text_field :price %>

    <p>

      <%= f.hidden_field :vendor_id, value: params[:id].to_i %>
      <!- - http://stackoverflow.com/questions/16280341/hidden-field-in-rails-form - ->

      <%= f.submit %>
    </p>
  <% end %> -->
  <form method="POST" action="/products#create">
    Product name <input name="name"/>
    Description <input name="description"/>
    Price <input name="price" type="number" step="0.01"/>
    <input type="hidden" name="vendor_id" value= <%= params.permit(:id)["id"].to_i %> />

    <input type="submit"/>

  </form>
</body>

app/views/vendors/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit <%= @vendor.name %> </title>
</head>

<body>
<form action= "/vendors/<%= @vendor.id %>" method="POST">
  <table>
  <input type="hidden" name="_method" value="PUT" />
  <tr><td>Name</td> <td><input name="vendor[name]" value= "<%= @vendor.name %>" /></td></tr>
  <tr><td>Market</td><td><input name="vendor[market_id]" value= "<%= @vendor.market_id %>" /></td></tr>
  <tr><td>Description</td><td><input name="vendor[description]" value= "<%= @vendor.description %>" /></td></tr>
  <tr><td>Website</td><td><input name="vendor[website]" value= "<%= @vendor.website %>" /></td></tr>
  <tr><td>Email</td><td><input name="vendor[email]" value= "<%= @vendor.email %>" /></td></tr>
  <tr><td>Phone</td><td><input name="vendor[phone]" value= "<%= @vendor.phone %>" /></td></tr>
  </table>
  <input type="submit" value="Save Changes"/>
  <a class="button" href="/vendors/<%= @vendor.id %>">Cancel</a>
</form>
</body>
</html>

app/views/vendors/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All vendors</title>
</head>

<body>

  <ul>
    <% Vendor.all.each do |vendor| %>
      <li>
        <a href="<%= vendor.path %>" > <%= vendor.name %> </a>
      </li>
    <% end %>
  </ul>
  <a class="button" href="/vendors/new">Sign up a new vendor</a>
</body>

</html>

app/views/vendors/login.html.erb
<form method="POST">
  Vendor ID: <input name="vendor[id]" type="number"/>
  <input type="submit" value="login"/>
</form>

app/views/vendors/login_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vendor login</title>
</head>

<body>
  <form method="POST">
    Vendor ID: <input name="id" type="number"/>
    <input type="submit" value="login"/>
  </form>
</body>
</html>

app/views/vendors/my_products.html.erb
<html>
<head>
  <title><%= @vendor.id %>'s products</title>
</head>

<body>
  <% current_user = @vendor.id == session[:vendor_id] %>
  <h2>
  <% if current_user %>
    My
  <% else %>
    <%= @vendor.name %>'s
  <% end %>
    products</h2>
  <ul>
  <% Product.where(vendor_id: @vendor.id).each do |product| %>
      <li><a href = <%= product.path %> ><%= product.name %></a> &mdash; <%= number_to_currency(product.price) %>
        <% if current_user %>
        <a class="button" href= "/sales/new/<%= product.id %>">Record Sale</a>
        <a class="button" href= <%= product.edit_path %> >Edit</a>
        <a class="button" href= <%= product.delete_path %> >Delete </a>
        <% end %> </li>
      <% end %>
  </ul>
  <a class="button" href="/vendors/<%= @vendor.id %>">Back to <%= @vendor.name %>'s page</a>
</body>
</html>

app/views/vendors/new.html.erb
<!DOCTYPE html>
<head>
  <title>Sign up a new vendor</title>
</head>

<body>
  <form method="POST" action="/vendors#create"><br>
    <table>
      <tr><td>Vendor name:</td><td><input name="vendor[name]"/></td></tr>
      <tr><td>Market id:</td><td><input name="vendor[market_id]"/></td></tr>
      <tr><td>Description:</td><td><input name="vendor[description]"/></td></tr>
      <tr><td>Website:</td><td><input name="vendor[website]"/></td></tr>
      <tr><td>Email:</td><td><input name="vendor[email]"/></td></tr>
      <tr><td>Phone:</td><td><input name="vendor[phone]"/></td></tr>
    </table>

    <input type="submit"/>

  </form>
  <a class="button" href="/vendors/">Cancel</a>
</body>
</html>

app/views/vendors/sales.html.erb
<h2>Sales Records for <%= @vendor.name %></h2>
<% results = 0 %>
<% @sales.each do |sale| %>
<% results += (sale.number_sold.to_i * sale.cost.to_f) %>
  <%= sale.number_sold %> <%= Product.find(sale.product_id).name %> sold at <%= sale.created_at %> for <%= number_to_currency(sale.cost) %>.<br>
<% end %>

Total sales revenue: <%= number_to_currency(results) %>
<br><a class="button" href="/vendors/<%= @vendor.id %>">Back to <%= @vendor.name %>'s page</a>

app/views/vendors/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All about <%= @vendor.name %></title>
</head>

<body>
  <% current_user = (session[:vendor_id] == @vendor.id) %>

  <h1><%= @vendor.name %></h1>
  <blockquote><%= @vendor.description %></blockquote>

  Email <a href="mailto:<%= @vendor.email %>"><%= @vendor.name %></a> or call <%= @vendor.phone %>.
  <% if @vendor.market_id %>
    <% @market = Market.find(@vendor.market_id) %>
    Or go find <a href="<%= @vendor.website %>"><%= @vendor.name %></a> at <a href="/markets/<%= @market.id %>"><%= @market.name %></a>.
  <% else %>
  <% end %>
  <% if current_user %>
    <br><br><a class="button" href="/vendors/<%=@vendor.id%>/edit">Edit profile</a>
    <a class="button" style="background-color: red" href="/vendors/<%=@vendor.id%>/destroy">Delete profile</a>
  <% end %>
  <h2><a href="/vendors/<%=@vendor.id%>/my_products"><%= @vendor.name %>'s Products</a></h2>
  <ul><% Product.where(vendor_id: @vendor.id).each do |product| %>
    <li><a href = <%= product.path %> ><%= product.name %></a> &mdash; <%= number_to_currency(product.price) %>
      <% if current_user %>
      <a class="button" href= "/sales/new/<%= product.id %>">Record Sale</a>
      <a class="button" href= <%= product.edit_path %> >Edit</a>
      <a class="button" href= <%= product.delete_path %> >Delete </a>
      <% end %> </li>
    <% end %>
  </ul>

  <% if current_user %>
    <a class="button" href="/vendors/<%=@vendor.id%>/add_product">Add a product</a>
    <a class="button" href="/vendors/<%=@vendor.id%>/sales">View Sales Record</a>
  <% end %>
  <a class="button" href="/vendors">Back to Vendor list</a>
</body>
</html>

app/views/vendors/vendor_page.html.erb
<% vendor = Vendor.find(params[:id]) %>

<html>
<head>
  <title><%= vendor.name %>'s Products</title>
</head>

<body>
  <h2><%= vendor.name %>'s Products</h2>
  <ul><% Product.where(vendor_id: vendor.id).each do |product| %>
    <li><a href = <%= product.path %> ><%= product.name %></a> &mdash; <%= number_to_currency(product.price) %></li>
    <% end %>
  </ul>

  <!-- This should appear only if user is logged in as this vendor -->
  <a href="/vendors/<%=vendor.id%>/add_product">Add a product</a>

</body>
</html>